### ISSUE TITLE
Reserved word "yield"

### ISSUE THREAD

**Issue by donundeen** [jedahan/collections-api#49]
trying to run
coffee -c server.coffee

gets:
/Users/undeed/.Trash/collections-api/server.coffee:18:34: error: reserved word "yield"

offending line is 
cache = ratelimit = -> (next) -> yield next

**Comment by jedahan** [comment]
I think just using the head version of coffeescript from https://github.com/jashkenas/coffeescript should do it.

**Comment by jedahan** [comment]
we are using javascript now
