### ISSUE TITLE
search endpoint isn't working

### ISSUE THREAD

**Issue by amycheng** [jedahan/collections-api#50]
the example provided for the `search` endpoint: `scrapi.org/search/mirror`

isn't yielding results (see this page from this [page](http://www.metmuseum.org/collection/the-collection-online/search?ft=mirror&amp;noqs=true)) .

**Comment by jedahan** [comment]
Wait, it still is returning empty stuff :(

**Comment by jedahan** [comment]
I've got an itching suspicion they are actively blocking scrapi...
