### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by sckott** [jedahan/collections-api#53]
getting 502 responses now

Any plans to bring back up?

**Comment by jedahan** [comment]
For sure, I will look into it this week. Sorry about that! (I should have some monitoring setup :) )

If you want to help work on either of these, or want help with whatever project you are trying to do, we could setup a time to hangout on irc/slack/gitter/whatever...

**Comment by sckott** [comment]
I am using in an R client https://github.com/ropensci/musemeta that has a set of scrapers/connectors to APIs for museum metadata - the API is preferable to scraping html that can change  - I'd be willing to help, but my JS is very minimal

**Comment by jedahan** [comment]
Should be working now!

**Comment by sckott** [comment]
awesome, thanks
